---

- name: Upload CloudFormation template to S3
  s3:
    profile: "{{aws_account_name}}"
    region: "{{region}}"
    bucket: meetup-ansible-deployment
    object: routes/route_tables.json
    src:  "{{role_path}}/templates/route_tables.json"
    mode: put    

- name: Launch CloudFormation
  cloudformation:
    stack_name: cfn-route-tables-stack-new
    state: "present"
    region: "{{region}}"
    template_url: "https://s3-ap-southeast-2.amazonaws.com/meetup-ansible-deployment/routes/route_tables.json"
    template_format: json
  register: cfn_output


- debug: msg="{{cfn_output}}"

- name: Delete CloudFormation template from S3
  s3:
    bucket: meetup-ansible-deployment
    object: routes/route_tables.json
    mode: delobj
    region: "{{region}}"

...
