---

- name: Get vpc facts for the local VPC 
  ec2_vpc_net_facts:
    region: ap-southeast-2
    profile: home
    filters:
      "tag:Name": cfn-vpc-yesterday
  register: vpc_facts

- name: set a local fact for the vpc id
  set_fact:
    vpc_id: "{{ vpc_facts.vpcs | map(attribute='id') | join }}"

- name: Create temporary directory to hold template files
  command: mktemp -d
  register: cf_temp_dir

- debug: msg="{{cf_temp_dir.stdout}}"  

- name: Generate cloudformation template with real values
  template: 
    src: "templates/subnets.json"
    dest: "{{cf_temp_dir.stdout}}/subnets.json"      

- name: Upload CloudFormation template to S3
  s3:
    profile: "{{aws_account_name}}"
    region: "{{region}}"
    bucket: meetup-ansible-deployment
    object: "subnets/subnets.json" 
    src:  "{{cf_temp_dir.stdout}}/subnets.json"
    mode: put    

- name: Launch CloudFormation
  cloudformation:
    stack_name: cfn-subnets-stack-yesterday
    state: "present"
    region: "{{region}}"
    template_url: "https://s3-ap-southeast-2.amazonaws.com/meetup-ansible-deployment/subnets/subnets.json"
    template_format: json
  register: cfn_output


- debug: msg="{{cfn_output}}"

- name: Delete CloudFormation template from S3
  s3:
    bucket: meetup-ansible-deployment
    object: subnets/subnets.json
    mode: delobj
    region: "{{region}}"

- name: Remove temporary directory
  file: 
    path: "{{cf_temp_dir.stdout}}"
    state: absent
    

...
